### PR TITLE
Write data to process.stdout directly if it's not TTY

### PR DESCRIPTION
**Pull request by joyeecheung**
Also make the stream written by the logger configurable so we can test it without monkey-patching process.stdout

With this we can close https://github.com/joyeecheung/node-core-utils/issues/35

screen shot 2017-11-02 at 5 45 37 pm

### CODE REVIEW

**Comment by joyeecheung** [comment]
Flaky errors? https://travis-ci.org/joyeecheung/node-core-utils/builds/296177546?utm_source=github_status&utm_medium=notification

```
27 passing (6s)
  1 failing
  1) auth
       asks for auth data if no ncurc is found:
     Error: Timeout of 1000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-core-utils@1.3.0 test-all: `mocha --require intelli-espower-loader test/**/*.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-core-utils@1.3.0 test-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-11-02T09_48_55_748Z-debug.log
```

Would need some time digging into the auth bit..

**Comment by Tiriel** [comment]
Maybe because of [travis-ci issue](https://www.traviscistatus.com/incidents/hjg5bwz1nvzr)?

**Comment by joyeecheung** [comment]
@Tiriel Yeah I've started another build and this time it's the "error occurred when generating build script" again, probably Travis is having another outage..

**Comment by cPhost** [comment]
@joyeecheung the flasky error is actually because the child process, `proc.on('close'` is not emitted under 1000 second timeout. Maye be extend the timeout in line 14:auth.test.js `this.timeout(3000)`.

**Comment by joyeecheung** [comment]
Travis is happy now, going to merge this because really want this feature so I can

```
git show -s --format=%B > msg.txt
echo "" >> msg.txt
get-metadata $ID >> msg.txt
git commit --amend -F msg.txt
```

**Comment by Tiriel** [comment]
@joyeecheung There seems indeed to be some flakiness.
I'm running the tests locally to check my own tests, and I just had the same error, but just once (on 30+ runs).
Maybe extend the timeout, like @cPhost said?

**Comment by joyeecheung** [comment]
@Tiriel We can try that, do you want to open a PR?

**Comment by Tiriel** [comment]
@joyeecheung No prob! Doing it right away

**Pull request merged**
